### ISSUE TITLE
Strategy Payload Error

### ISSUE THREAD

**Issue by AxanIqbal** [Mawi137/passport-firebase-jwt#12]
```
ReferenceError: payload is not defined
    at FirebaseAuthStrategy.FirebaseJwtStrategy.authenticate (C:\Users\ahsan\project\node_modules\passport-firebase-jwt\lib\strategy.js:56:22)
    at attempt (C:\Users\ahsan\project\node_modules\passport\lib\middleware\authenticate.js:360:16)
    at authenticate (C:\Users\ahsan\project\node_modules\passport\lib\middleware\authenticate.js:361:7)
    at C:\Users\ahsan\project\node_modules\@nestjs\passport\dist\auth.guard.js:91:3
    at new Promise (<anonymous>)
    at C:\Users\ahsan\project\node_modules\@nestjs\passport\dist\auth.guard.js:83:83
    at FirebaseAuthGuard.<anonymous> (C:\Users\ahsan\project\node_modules\@nestjs\passport\dist\auth.guard.js:49:36)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ahsan\project\node_modules\@nestjs\passport\dist\auth.guard.js:17:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Should be self.payload ? instead of just payload

**Comment by Mawi137** [comment]
Hi thanks, little mistake on my end, thanks for reporting it! Fixed in 1.2.1.
